"use client"

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/PWakSvNUGYf
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "../ui/button"
import { AuroraBackground } from "../ui/aurora-background"
import { motion } from "framer-motion"

export default function Hero() {
  return (
    <AuroraBackground>
      <motion.div
        initial={{ opacity: 0.0, y: 40 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{
          delay: 0.3,
          duration: 0.8,
          ease: "easeInOut",
        }}
        className="flex flex-col items-center justify-center h-[calc(100dvh-64px)]"
      >
        <section className="w-full h-full py-12 md:py-24 lg:py-32 xl:py-48 flex flex-col items-center justify-center z-50">
          <div className="container px-4 md:px-6 text-center ">
            <div className="max-w-3xl mx-auto space-y-6">
              <h1 className="text-4xl font-extrabold tracking-tight text-gray-50 sm:text-5xl md:text-6xl lg:text-7xl">
                Ace Your Next Interview with AI
              </h1>
              <p className="text-lg text-gray-400 md:text-xl">
                Our AI-powered interview preparation software analyzes job
                descriptions to provide personalized insights and practice
                sessions, helping you confidently navigate any interview.
              </p>
              <div>
                <Button asChild size="lg" className="text-md">
                  <Link href="#" prefetch={false}>
                    Get Started
                  </Link>
                </Button>
              </div>
            </div>
          </div>
        </section>
      </motion.div>
    </AuroraBackground>
  )
}
